### ISSUE TITLE
"Download Report" feature: not capturing title, details of the viz

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/schemes-dashboard#2]
The "Download Report" feature is not capturing the title and other details of the viz - i.e. I only get the table/map viz w/o details on which indicator it belongs to. This renders the viz less useful.

**Comment by shivamragnar** [comment]
@aruncdl Can you check and close this issue?

**Comment by arunsud** [comment]
While the title and indicator details are now being captured, longer viz titles are creating issues.

**Comment by gggodhwani** [comment]
@aruncdl Sharing a snapshot of this edge case might be helpful?

**Comment by PixeledCode** [comment]
tracking #9 for this
