### ISSUE TITLE
Updating page titles with appropriate nomenclature

### ISSUE THREAD

**Issue by gggodhwani** [cbgaindia/schemes-dashboard#6]
The names which are being index by Google & other search engines are quite limiting, one can have a look by searching: **site:schemes.openbudgetsindia.org**, we always get title as "Schemes Dashboard | Open Budgets India". We rather need a title as **[Scheme Name]([Scheme Slug/Acronym]) State-wise Budget & Expenditure | Open Budgets India**

**Comment by Abhi2102** [comment]
changed the title, og:title and twitter:title.
